catalogMode: strict
shellEmulator: true
trustPolicy: no-downgrade
linkWorkspacePackages: true
packages:
  - packages/*
  - apps/*

catalogs:
  devtool:
    '@withxat/eslint-config': ^1.1.1
    '@withxat/tsconfig': ^1.0.1
    eslint: ^10.0.3
    jiti: ^2.6.1
    lefthook: ^2.1.4
    turbo: ^2.8.19
    typescript: ^5.9.3
  react:
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.2.3
    react: ^19.2.4
    react-dom: ^19.2.4
  tailwind:
    tailwindcss: ^4.2.2

allowBuilds:
  lefthook: true
