packages:
  - packages/*
  - apps/*

catalogs:
  devtool:
    '@withxat/eslint-config': ^1.0.3
    '@withxat/tsconfig': ^1.0.0
    eslint: ^9.39.2
    jiti: ^2.6.1
    lefthook: ^2.0.16
    typescript: ^5.9.3

onlyBuiltDependencies:
  - lefthook
